-- ============================================================
--  BERIYU — Skema database Supabase
--  Jalankan di: Supabase Dashboard > SQL Editor > New query > Run
-- ============================================================

-- ---------- TABEL MENU ----------
create table if not exists public.menu (
  id         bigint generated by default as identity primary key,
  nama       text not null,
  kat        text not null default 'Kopi',
  harga      integer not null default 0,
  promo      integer not null default 0,      -- 0 = tanpa harga promo
  desk       text,
  emoji      text default '☕',
  foto_url   text,                            -- URL foto dari storage
  aktif      boolean not null default true,
  created_at timestamptz default now()
);

-- ---------- TABEL PROMO / VOUCHER ----------
create table if not exists public.promo (
  id         bigint generated by default as identity primary key,
  judul      text not null,
  sub        text,
  kode       text not null,
  aktif      boolean not null default true,
  created_at timestamptz default now()
);

-- ---------- TABEL PESANAN ----------
create table if not exists public.pesanan (
  id         bigint generated by default as identity primary key,
  kode       text not null,
  items      jsonb not null,                  -- [{nama,qty,harga}]
  subtotal   integer not null default 0,
  diskon     integer not null default 0,
  ongkir     integer not null default 0,
  total      integer not null default 0,
  metode     text not null default 'antar',
  nama       text,
  hp         text,
  alamat     text,
  catatan    text,
  status     text not null default 'Diproses',
  waktu      timestamptz default now()
);

-- ============================================================
--  ROW LEVEL SECURITY
--  Publik: boleh BACA menu & promo, boleh BUAT pesanan.
--  Tulis menu/promo & baca pesanan: hanya user login (admin).
-- ============================================================
alter table public.menu    enable row level security;
alter table public.promo   enable row level security;
alter table public.pesanan enable row level security;

-- MENU: semua boleh baca
create policy "menu baca publik" on public.menu
  for select using (true);
-- MENU: hanya user login boleh tulis/ubah/hapus
create policy "menu tulis admin" on public.menu
  for all using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');

-- PROMO: semua boleh baca
create policy "promo baca publik" on public.promo
  for select using (true);
create policy "promo tulis admin" on public.promo
  for all using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');

-- PESANAN: siapa pun boleh membuat (checkout dari publik)
create policy "pesanan buat publik" on public.pesanan
  for insert with check (true);
-- PESANAN: hanya admin boleh membaca daftar pesanan
create policy "pesanan baca admin" on public.pesanan
  for select using (auth.role() = 'authenticated');
-- PESANAN: hanya admin boleh mengubah status pesanan
create policy "pesanan ubah admin" on public.pesanan
  for update using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');
-- PESANAN: hanya admin boleh menghapus (dipakai pembersihan histori >30 hari)
create policy "pesanan hapus admin" on public.pesanan
  for delete using (auth.role() = 'authenticated');

-- ============================================================
--  HISTORI PESANAN — hapus otomatis setelah 30 hari
--  Butuh extension pg_cron aktif: Dashboard > Database > Extensions > pg_cron.
--  Selain cron ini, aplikasi juga membersihkan data >30 hari tiap admin
--  membuka dashboard (fallback kalau pg_cron belum aktif).
-- ============================================================
select cron.schedule(
  'hapus-pesanan-lama',
  '0 3 * * *',
  $$ delete from public.pesanan where waktu < now() - interval '30 days'; $$
);

-- ============================================================
--  CEK STATUS PESANAN (publik, tanpa login)
--  Dipakai tab "Pesanan saya" — cocokkan kode + no. HP supaya
--  publik tidak bisa mengintip pesanan orang lain.
-- ============================================================
create or replace function public.cek_status_pesanan(p_kode text, p_hp text)
returns table(status text, waktu timestamptz)
language sql security definer set search_path = public as $$
  select status, waktu from public.pesanan
  where kode = p_kode and hp = p_hp
  limit 1;
$$;

grant execute on function public.cek_status_pesanan(text, text) to anon, authenticated;

-- ============================================================
--  STORAGE — bucket foto menu
--  Bisa juga dibuat lewat Dashboard > Storage > New bucket (public).
-- ============================================================
insert into storage.buckets (id, name, public)
values ('menu-foto', 'menu-foto', true)
on conflict (id) do nothing;

-- Semua boleh melihat foto
create policy "foto baca publik" on storage.objects
  for select using (bucket_id = 'menu-foto');
-- Hanya admin (login) boleh upload / hapus foto
create policy "foto upload admin" on storage.objects
  for insert with check (bucket_id = 'menu-foto' and auth.role() = 'authenticated');
create policy "foto hapus admin" on storage.objects
  for delete using (bucket_id = 'menu-foto' and auth.role() = 'authenticated');

-- ============================================================
--  DATA CONTOH (opsional — hapus kalau mau mulai kosong)
-- ============================================================
insert into public.menu (nama,kat,harga,promo,desk,emoji,aktif) values
 ('Kopi Susu Beriyu','Kopi',22000,0,'Espresso, susu segar, gula aren cair. Signature kami.','☕',true),
 ('Americano Panas','Kopi',18000,0,'Dua shot espresso, air panas. Pahitnya pas.','☕',true),
 ('Es Cokelat Klasik','Non-Kopi',20000,16000,'Cokelat pekat, susu, es batu.','🥤',true),
 ('Matcha Latte','Non-Kopi',25000,0,'Matcha premium dengan susu creamy.','🍵',true),
 ('Nasi Ayam Bakar Madu','Makanan Berat',32000,0,'Ayam bakar madu, nasi hangat, sambal.','🍗',true),
 ('Mie Goreng Beriyu','Makanan Berat',26000,22000,'Mie goreng telur, ayam suwir, kerupuk.','🍜',true),
 ('Kentang Goreng','Camilan',18000,0,'Kentang renyah, saus keju atau sambal.','🍟',true);

insert into public.promo (judul,sub,kode,aktif) values
 ('Diskon Sore','Potongan 20% jam 15–18','SORE20',true),
 ('Gratis Ongkir','Min. belanja Rp50rb','ONGKIRGRATIS',true);
